import type { EquipmentConfig } from '../../types/equipment'

export const equipmentConfigs: Record<string, EquipmentConfig> = {
  'incoming-sources': {
    type: 'incoming-sources',
    title: 'Incoming Sources',
    endpoint: 'incoming-sources',
    route: '/assets/incoming-sources',
    primaryField: 'sourceName',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'sourceName', label: 'Source Name', sortable: true },
      { key: 'sourceType', label: 'Source Type', sortable: true },
      { key: 'voltageLevelKv', label: 'Voltage KV', sortable: true },
      { key: 'feederName', label: 'Feeder', sortable: true },
      { key: 'meterNumber', label: 'Meter', sortable: true },
    ],
    fields: [
      { name: 'sourceName', label: 'Source Name', type: 'text', required: true },
      { name: 'sourceType', label: 'Source Type', type: 'text' },
      { name: 'voltageLevelKv', label: 'Voltage Level KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'feederName', label: 'Feeder Name', type: 'text' },
      { name: 'meterNumber', label: 'Meter Number', type: 'text' },
    ],
    numericFilters: [{ name: 'voltageLevelKv', label: 'Voltage KV', type: 'number' }],
  },
  'outgoing-feeders': {
    type: 'outgoing-feeders',
    title: 'Outgoing Feeders',
    endpoint: 'outgoing-feeders',
    route: '/assets/outgoing-feeders',
    primaryField: 'feederName',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'feederName', label: 'Feeder Name', sortable: true },
      { key: 'feederCode', label: 'Code', sortable: true },
      { key: 'voltageLevelKv', label: 'Voltage KV', sortable: true },
      { key: 'feederType', label: 'Type', sortable: true },
      { key: 'connectedLoadMw', label: 'Load MW', sortable: true },
    ],
    fields: [
      { name: 'feederName', label: 'Feeder Name', type: 'text', required: true },
      { name: 'feederCode', label: 'Feeder Code', type: 'text' },
      { name: 'voltageLevelKv', label: 'Voltage Level KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'feederType', label: 'Feeder Type', type: 'text' },
      { name: 'connectedLoadMw', label: 'Connected Load MW', type: 'number', min: 0, step: '0.01' },
    ],
    numericFilters: [{ name: 'voltageLevelKv', label: 'Voltage KV', type: 'number' }],
    textFilters: [{ name: 'feederType', label: 'Feeder Type', type: 'text' }],
  },
  transformers: {
    type: 'transformers',
    title: 'Transformers',
    endpoint: 'transformers',
    route: '/assets/transformers',
    primaryField: 'transformerCode',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'transformerCode', label: 'Code', sortable: true },
      { key: 'capacityMva', label: 'Capacity MVA', sortable: true },
      { key: 'primaryVoltageKv', label: 'Primary KV', sortable: true },
      { key: 'secondaryVoltageKv', label: 'Secondary KV', sortable: true },
      { key: 'make', label: 'Make', sortable: true },
      { key: 'serialNumber', label: 'Serial', sortable: true },
    ],
    fields: [
      { name: 'transformerCode', label: 'Transformer Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'capacityMva', label: 'Capacity MVA', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'primaryVoltageKv', label: 'Primary Voltage KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'secondaryVoltageKv', label: 'Secondary Voltage KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'make', label: 'Make', type: 'text' },
      { name: 'serialNumber', label: 'Serial Number', type: 'text' },
      { name: 'commissioningDate', label: 'Commissioning Date', type: 'date' },
    ],
    numericFilters: [{ name: 'capacityMva', label: 'Capacity MVA', type: 'number' }],
  },
  'lightning-arresters': {
    type: 'lightning-arresters',
    title: 'Lightning Arresters',
    endpoint: 'lightning-arresters',
    route: '/assets/lightning-arresters',
    primaryField: 'arresterCode',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'arresterCode', label: 'Code', sortable: true },
      { key: 'locationDescription', label: 'Location', sortable: true },
      { key: 'voltageRatingKv', label: 'Voltage KV', sortable: true },
      { key: 'make', label: 'Make', sortable: true },
      { key: 'serialNumber', label: 'Serial', sortable: true },
    ],
    fields: [
      { name: 'arresterCode', label: 'Arrester Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'locationDescription', label: 'Location Description', type: 'text' },
      { name: 'voltageRatingKv', label: 'Voltage Rating KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'make', label: 'Make', type: 'text' },
      { name: 'serialNumber', label: 'Serial Number', type: 'text' },
      { name: 'installationDate', label: 'Installation Date', type: 'date' },
    ],
    numericFilters: [{ name: 'voltageRatingKv', label: 'Voltage KV', type: 'number' }],
  },
  'battery-banks': {
    type: 'battery-banks',
    title: 'Battery Banks',
    endpoint: 'battery-banks',
    route: '/assets/battery-banks',
    primaryField: 'batteryBankCode',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'batteryBankCode', label: 'Code', sortable: true },
      { key: 'batteryType', label: 'Type', sortable: true },
      { key: 'voltageV', label: 'Voltage V', sortable: true },
      { key: 'capacityAh', label: 'Capacity Ah', sortable: true },
      { key: 'cellCount', label: 'Cells', sortable: true },
      { key: 'make', label: 'Make', sortable: true },
    ],
    fields: [
      { name: 'batteryBankCode', label: 'Battery Bank Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'batteryType', label: 'Battery Type', type: 'text' },
      { name: 'voltageV', label: 'Voltage V', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'capacityAh', label: 'Capacity Ah', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'cellCount', label: 'Cell Count', type: 'number', min: 0, step: '1' },
      { name: 'make', label: 'Make', type: 'text' },
      { name: 'installationDate', label: 'Installation Date', type: 'date' },
    ],
    numericFilters: [{ name: 'voltageV', label: 'Voltage V', type: 'number' }],
    textFilters: [{ name: 'batteryType', label: 'Battery Type', type: 'text' }],
  },
  'capacitor-banks': {
    type: 'capacitor-banks',
    title: 'Capacitor Banks',
    endpoint: 'capacitor-banks',
    route: '/assets/capacitor-banks',
    primaryField: 'capacitorBankCode',
    defaultSortBy: 'createdAt',
    columns: [
      { key: 'capacitorBankCode', label: 'Code', sortable: true },
      { key: 'capacityMvar', label: 'Capacity MVAR', sortable: true },
      { key: 'voltageLevelKv', label: 'Voltage KV', sortable: true },
      { key: 'stepsCount', label: 'Steps', sortable: true },
      { key: 'make', label: 'Make', sortable: true },
    ],
    fields: [
      { name: 'capacitorBankCode', label: 'Capacitor Bank Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'capacityMvar', label: 'Capacity MVAR', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'voltageLevelKv', label: 'Voltage Level KV', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'stepsCount', label: 'Steps Count', type: 'number', min: 0, step: '1' },
      { name: 'make', label: 'Make', type: 'text' },
      { name: 'installationDate', label: 'Installation Date', type: 'date' },
    ],
    numericFilters: [{ name: 'capacityMvar', label: 'Capacity MVAR', type: 'number' }],
  },
}
